# -*- coding: utf-8 -*-
"""PythonClassNote.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1WRW9C-cu3QWMgsUexb_iBLKHA5kMB06Q
"""

print("Hello World !!! Love you All ❤")

# we will learn 2 Things

# 1 -> Data Storing

# 2 -> How to use that data and write logic and get outputs

# 3 -> How to augment that Data

# Declaring Data type in a variable

a = 10

print (a)

b = 20

print (b)

type (a)

type (b)

c = 31.8

type (c)

d = ' Sarthak How are you ??? '

type (d)

e =True

e

type(e)

f = True

g = False

h = 'I am 17 '

type (h)

"""#List"""

# List = order Sequence of Object

lt = [23,46,27,91,45,78]

lt

lt2 = [23,46,33.5,12.5,25.9,6.6,True,'Abhishek']

lt2

lt3 = [12,5.6,'Vivek',True,lt,lt2]

lt3

lt3[0]

lt3[2]

lt3[5]

lt3[5][4]

# Dict

vivek = [23,'8767867823','dewas','vivek@gmail.com']

vivek

vivek[3]

# Dict
# Unordered Collection of Key Value Pairs

dt = {'name':'Vivek','email':'vivek@gmail.com','location':'Dewas','age':23}

dt['name']

dt['age']

st = {'sai@itm.edu','sai@itm.edu','sai@gmail.com','sai@yahoo.com','sai@itm.edu'}

st

#tuple

tp = ('LetsUpgrade','AI','AR/VR')

tp  [0]

tp.index('AI')

# Built in methods of List

lst = [1,2,3,4,'sai','mack','sharmila']

lst

lst.append('raju')

lst

lst.index('sharmila')

lst[6]

lst.pop()

lst

lst.remove('sai')

lst

lst.insert(5,'manoj')

lst

dit = {'name':'naveen','age':26,'email':'naveen@lu.in','mobile':'8768768767'}

dit

dit.keys()

dit.values()

dit.get('email')

dit['email']

dit.get('location')

dit['location']

dit.clear()

dit

dit.update({'name':'zeba'})

dit

"""# Control Flow"""

# Comparison Operator

# Equal to ? -> ==

a = 10
b = 10

( a == b)

c = 20

(a == c)

# Not Equal to ? -> !=

(a != b)

(a != c)

# greater than ? -> >

(a > b)

( a > c)

# Less Than or equal to ? -> <=

a <= b

a <= c

# Greater than or equal to ? -> >=

a >= b

a >= c

# Logical comparison operator

# And
# or
# Not

tf_light = 'green'
tf_infront = 'empty'

tf_light == 'green' and tf_infront == 'empty'

tf_light == 'red' and tf_infront == 'empty'

tf_light == 'green' and tf_infront == 'not empty'

True and True

True and False

False and True

False and False

"""# If Else"""

if_hungry = 'yes'

if (if_hungry == 'yes'):
  print("Order Food To Zomato")
  print("May be Order Chicken")
  print("Pay From ICICI Card")
else:
  print("Ignore and do nothing")

# If elif else

marks = 81
if marks > 90:
  print("A++")
elif marks > 80:
  print("A+")
elif marks > 60:
  print("A")
elif marks > 50:
  print ("B")
else:
  print("Ok Good")

# Lets build a calculator using If Elif and Else

num1 = int(input('enter Number 1 -'))

num2 = int(input('enter Number 2 -'))

operation = input("Enter the operation that you want to do ? (+,-,*,/):")

if operation == '-':
  print(num1 -num2)
elif operation == '+':
  print(num1 + num2)
elif operation == '*':
  print(num1 * num2)
elif operation == '/':
  print(num1 / num2)
else:
  print("Give a valid operator as a input !!")

"""# For Loop"""



lt = ['sai','nitin','yadav','coder','sri']

lt

for temp in lt:
  print(temp)

for temp in lt:
  print(temp)
else:
  print("We are done with the Loop!!")

# Wap to print a 12 ka table using for loop

"""# Double-click(or enter) to edit"""



for temp in range(11):
  print(temp)

for mahir in range(1,11):
  print("12 x",mahir,'=',mahir*12)
else:
  print("Hey we are done with a table program!!")

# while loop

want_to_play_again = 'y'

while want_to_play_again == 'y':
  want_to_play_again = input("Do you want to play again ? (y/n) -")
else:
  print("Hey we are done with this while loop !!!")

fl = open("hello.txt",'w')
fl.write("Rishu, Rahul, Sarthak, Sarthak")
fl.close()

fl = open("hello.txt", 'r')
temp_st = fl.read()
fl.close()

temp_st

fl = open("hello.txt", 'a')
fl.write("Sai,Teja,Sri,Pooja")
fl.close()

fl = open("hello.txt",'r')
temp_st = fl.read()
fl.close()

temp_st

fl = open("hello.txt", 'a')
fl.write("\n\n Nilesh,Sarthak,Gupta")
fl.close()

fl = open("hello.txt",'r')
temp_st = fl.read()
fl.close()

print(temp_st)

fl = open("new_file.txt",'r')
print(fl.read())
fl.close()

"""# Function"""

def hello():
  print("hey")
  print("How are you ???")
  print("How was ur day ???")
  print("Eat on time, sleep on time !!")

hello()

def answer():
  print("Hey")
  print("Am good")
  print("day was good")
  print("yes eating of time, taking on care time!!")

answer()

def hello(name):
  print("hey",name)
  print("how are you???")
  print(name, "how was ur day")
  print(name , "eat on time sleep on time!!!")

hello("rahul")

hello("nilesh")

def calculator(num1,num2,ops):
  result = 0
  if ops == "+":
    result = num1 + num2
  elif ops == "-":
    result = num1 - num2

  elif ops == "*":
    result = num1 * num2
  elif ops == "/":
    result = num1 / num2

  else:
    result = "give a valid ops"
  print(result)
  return result